packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/js': ^9.39.1
  '@next/eslint-plugin-next': 16.0.10
  '@tailwindcss/postcss': ^4.1.17
  '@types/eslint': ^9
  '@types/node': ^24
  eslint: ^9.39.1
  lucide-react: 0.560.0
  next: 16.0.10
  prettier: ^3.6.2
  tailwindcss: ^4.1.17
  typescript: ^5.9.3

catalogs:
  react19:
    '@types/react': ^19.2
    '@types/react-dom': ^19.2
    react: 19.2.3
    react-dom: 19.2.3
